index:
    path: /
    controller: App\Controller\HubController::index
    methods:
        - GET
        - POST

search:
    path: /search
    controller: App\Controller\HubController::index
    methods:
        - GET